In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [3]:
movies = movies.merge(credits , on = 'title')

In [41]:
movies.iloc[1]
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4806 entries, 0 to 4808
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4806 non-null   object
 1   id        4806 non-null   int64
 2   keywords  4806 non-null   object
 3   title     4806 non-null   object
 4   cast      4806 non-null   object
 5   crew      4806 non-null   object
 6   overview  4806 non-null   object
 7   tag       4806 non-null   object
dtypes: int64(1), object(7)
memory usage: 337.9+ KB

In [5]:
# genre , id , keywords , title , cast , crew , overview

movies = movies[['genres' , 'id' , 'keywords' ,'title' , 'cast' , 'crew' , 'overview' ]]
movies.head(1)

,genres,id,keywords,title,cast,crew,overview
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."

In [6]:
movies = movies.dropna().copy()
movies.head(1)

,genres,id,keywords,title,cast,crew,overview
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."

In [7]:
import ast
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [8]:
def convert3(text):
    counter = 0
    l = []

    for i in ast.literal_eval(text):
        if counter <3 :
            l.append(i['name'])
            counter+=1
    return l

In [9]:
movies['genres'] = movies['genres'].apply(convert)

In [42]:
movies.head(1)

,genres,id,keywords,title,cast,crew,overview,tag
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction, c..."

In [11]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head(1)

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."

In [12]:
movies['cast'] = movies['cast'].apply(convert3)
movies.head(1)

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."

In [13]:
def convert_dir(text):
    counter = 0
    l = []

    for i in ast.literal_eval(text) :
        if i['job'] == 'Director' :
            l.append(i['name'])
    return l

In [14]:
movies['crew'] = movies['crew'].apply(convert_dir)

In [15]:
movies

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"In the 22nd century, a paraplegic Marine is di..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"Captain Barbossa, long believed to be dead, ha..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],A cryptic message from Bond’s past sends him o...
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],Following the death of District Attorney Harve...
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,"[united states–mexico barrier, legs, arms, pap...",El Mariachi,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez],El Mariachi just wants to play his guitar and ...
4805,"[Comedy, Romance]",72766,[],Newlyweds,"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns],A newlywed couple's honeymoon is upended by th...
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"[date, love at first sight, narration, investi...","Signed, Sealed, Delivered","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith],"""Signed, Sealed, Delivered"" introduces a dedic..."
4807,[],126186,[],Shanghai Calling,"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia],When ambitious New York attorney Sam is sent t...
4808,[Documentary],25975,"[obsession, camcorder, crush, dream girl]",My Date with Drew,"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Brian Herzlinger, Jon Gunn, Brett Winn]",Ever since the second grade when he first saw ...

In [16]:
movies['overview']=movies['overview'].apply(lambda x : x.split())

In [17]:
movies.head(1)

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [18]:
movies['genres'] = movies['genres'].apply(lambda x : [i.replace(" " , "") for i in x])

In [19]:
movies.head(1)

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [20]:
movies['keywords'] = movies['keywords'].apply(lambda x : [i.replace(" " , "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x : [i.replace(" " , "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x : [i.replace(" " , "") for i in x])
movies['overview'] = movies['overview'].apply(lambda x : [i.replace(" " , "") for i in x])

In [21]:
movies.head(1)

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [22]:
movies['tag'] = movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew'] + movies['overview']
movies.head()

,genres,id,keywords,title,cast,crew,overview,tag
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction, c..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime, spy, basedonnovel, ..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller, dccomics, cri..."
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction, basedonnov..."

In [23]:
new_df = movies[['id' , 'title' , 'tag']]
new_df.head()

,id,title,tag
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."

In [24]:
new_df['tag'] = new_df['tag'].apply(lambda x : " ".join(x))

C:\Users\harsh\AppData\Local\Temp\ipykernel_2268\1149718486.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].apply(lambda x : " ".join(x))

In [25]:
new_df['tag'] = new_df['tag'].apply(lambda x :x.lower())

C:\Users\harsh\AppData\Local\Temp\ipykernel_2268\3860499484.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].apply(lambda x :x.lower())

In [26]:
new_df.head()

,id,title,tag
0,19995,Avatar,action adventure fantasy sciencefiction cultur...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...
2,206647,Spectre,action adventure crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,action crime drama thriller dccomics crimefigh...
4,49529,John Carter,action adventure sciencefiction basedonnovel m...

# Text to Vector 
Now we convert the text to vector to get the similarity between two movies that we are going to recommend to the user
There are some techniques to do that , those are : 
1. Bag of Words
2. tfidf
3. word2vec

but we are using Bag of words for this

In [27]:
# using stem to make similar words same for ex.. dance dancing danced all are same 

from nltk.stem.porter import PorterStemmer 

ps = PorterStemmer()

In [28]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [29]:
new_df['tag'] = new_df['tag'].apply(stem)

C:\Users\harsh\AppData\Local\Temp\ipykernel_2268\4074900442.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].apply(stem)

In [30]:
new_df['tag']

0       action adventur fantasi sciencefict culturecla...
1       adventur fantasi action ocean drugabus exotici...
2       action adventur crime spi basedonnovel secreta...
3       action crime drama thriller dccomic crimefight...
4       action adventur sciencefict basedonnovel mar m...
                              ...
4804    action crime thriller unitedstates–mexicobarri...
4805    comedi romanc edwardburn kerrybishé marshadiet...
4806    comedi drama romanc tvmovi date loveatfirstsig...
4807    danielhenney elizacoup billpaxton danielhsia w...
4808    documentari obsess camcord crush dreamgirl dre...
Name: tag, Length: 4806, dtype: object

In [31]:
# string to Vector 

from sklearn.feature_extraction.text import CountVectorizer

In [32]:
cv = CountVectorizer(max_features=5000 , stop_words='english')

vectors = cv.fit_transform(new_df['tag']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
# Tells the 5000 words that we took

cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [34]:
# We are using cosine distance to tell the similarity bw two tags(better than eucladian distance in higher dimension)

from sklearn.metrics.pairwise import cosine_similarity

In [35]:
similarity = cosine_similarity(vectors)
similarity[0]

new_df.head()

,id,title,tag
0,19995,Avatar,action adventur fantasi sciencefict culturecla...
1,285,Pirates of the Caribbean: At World's End,adventur fantasi action ocean drugabus exotici...
2,206647,Spectre,action adventur crime spi basedonnovel secreta...
3,49026,The Dark Knight Rises,action crime drama thriller dccomic crimefight...
4,49529,John Carter,action adventur sciencefict basedonnovel mar m...

In [36]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    
    distances = similarity[movie_index]

    # hold the real index of the movie for comparision 
    movie_list = sorted(list(enumerate(distances)) , reverse = True , key = lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

movies['title'].head()

0                                      Avatar
1    Pirates of the Caribbean: At World's End
2                                     Spectre
3                       The Dark Knight Rises
4                                 John Carter
Name: title, dtype: object

In [37]:
recommend('Spectre')

Quantum of Solace
Skyfall
Never Say Never Again
From Russia with Love
Octopussy

In [38]:
import pickle

In [39]:
pickle.dump(new_df.to_dict() , open('movie_dict.pkl' , 'wb'))

In [40]:
pickle.dump(similarity, open('similarity.pkl' ,'wb' ))